const signformstyles = {
  cover: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
  },
  formUI: {
    position: "relative",
  },
  form: {
    width: "320px",
    height: "540px",
    padding: "25px",
    backgroundColor: "#fff",
    boxShadow: "0px 15px 60px #000000",
    borderRadius: "20px",
    position: "relative",
  },
  closeForm: {
    position: "absolute",
    top: "23px",
    right: "25px",
    width: "24px",
    height: "24px",
    cursor: "pointer",
    backgroundColor: "transparent",
  },
  formBody: {
    position: "absolute",
    top: "50%",
    right: "25px",
    left: "25px",
    width: "270px",
    transform: "translateY(-50%)",
    margin: "0 auto",
  },
  welcomeLines: {
    textAlign: "center",
    lineHeight: 1,
  },
  welcomeLines1: {
    textAlign: "center",
    lineHeight: 1,
    fontSize: "13.4px",
    marginTop: "5px",
  },
  welcomeLines2: {
    textAlign: "center",
    lineHeight: 1,
    fontSize: "13.4px",
    marginTop: "5px",
    color: "#f5506e",
  },
  wLine1: {
    color: "#7f7f7f",
    fontSize: "40px",
  },
  wLine2: {
    color: "#9c9c9c",
    fontSize: "28px",
    marginTop: "17px",
  },
  inputArea: {
    marginTop: "40px",
  },
  fInp: {
    padding: "11px 25px",
    border: "1px solid #e3e3e3",
    lineHeight: 1,
    borderRadius: "20px",
    marginBottom: "15px",
  },
  input: {
    width: "100%",
    fontSize: "13.4px",
    padding: 0,
    margin: 0,
    border: 0,
    color: "#000000",
    outline: "none",
    boxShadow: "none",
  },
  submitButtonCvr: {
    marginTop: "20px",
  },
  submitButton: {
    display: "block",
    width: "100%",
    color: "#fff",
    fontSize: "14px",
    margin: 0,
    padding: "14px 13px 12px 13px",
    border: 0,
    backgroundColor: "#f5506e",
    borderRadius: "25px",
    lineHeight: 1,
    cursor: "pointer",
  },
  forgotPass: {
    textAlign: "center",
    marginTop: "10px",
  },
  forgotPassLink: {
    color: "#868686",
    fontSize: "12px",
    textDecoration: "none",
  },
  bar: {
    position: "absolute",
    left: "50%",
    bottom: "-50px",
    width: "28px",
    height: "8px",
    marginLeft: "-33px",
    backgroundColor: "#dfdfdf",
    borderRadius: "10px",
  },
};

export default signformstyles;
